server:
  port: 8080 # 내장 톰캣 포트번호

spring:
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB 연결 주소 (Embedded Mode)
    username: username        # H2 DB 접속 ID (사용자 지정)
    password: password        # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

jwt:
  token-secret-key: ThisIsTempSecretKeyWaitForMeThisIsTempSecretKeyWaitForMeThisIsTempSecretKeyWaitForMe
  access-token-valid-time: 1800000   # 30분
  refresh-token-valid-time: 3600000

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: dev-wait-for-me
    credentials:
      access-key: access-key
      secret-key: secret-key
sms:
  fromNumber: 01012345678
  apiKey: api-key
  apiSecretKey: api-secret-key

totp:
  secret: ThisIsTempSecretKeyWaitForMeThisIsTempSecretKeyWaitForMeThisIsTempSecretKeyWaitForMe
  validTime: 120000      # ms 기준

springdoc:
  packages-to-scan: org.waitforme.backend.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

management:
  endpoints:
    web:
      base-path: /     # http://localhost:8080/health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

firebase:
  url: https://fcm.googleapis.com/v1/projects/wait-for-me-411809/messages:send
